### ISSUE TITLE
[M1] Add Benchmark results to revision control

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/mina-rs#120]
**Task summary**

**Specification reference**

- Add Benchamark results to revision control

@jspada Plz take a look at https://github.com/ChainSafe/mina-rs/pull/94#discussion_r778173959

This does not seem to be feasible because [GH actions](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#cloud-hosts-for-github-hosted-runners) use azure [DSv2-series VMs](https://docs.microsoft.com/en-us/azure/virtual-machines/dv2-dsv2-series#dsv2-series) which has a pool of CPU models released from 2013-2019, it's not possible to fix a CI job to a certain CPU model so that either the comparison or the alert that use historical data tend to be invalid.

> GitHub hosts Linux and Windows runners on Standard_DS2_v2 virtual machines in Microsoft Azure with the GitHub Actions runner application installed.

> DSv2-series sizes run on Intel® Xeon® Platinum 8272CL (Cascade Lake), Intel® Xeon® 8171M 2.1GHz (Skylake) or the the Intel® Xeon® E5-2673 v4 2.3 GHz (Broadwell) or the Intel® Xeon® E5-2673 v3 2.4 GHz (Haswell) processors with Intel Turbo Boost Technology 2.0 and use premium storage.

**Other information and links**

**Comment by jspada** [comment]
That's annoying, but what can we do.  Perhaps, alternatively, just use the lower-bound to check for broken performance.  For example, if 1000 deserializations take 10ms on the slowest (e.g. 2013) CPU, then put an `assert(time_test() < 20ms);`  This way you will catch it if someone breaks something bad.

**Comment by jspada** [comment]
nice - thanks
