### ISSUE TITLE
Using mina-rs in a mobile app

### ISSUE THREAD

**Issue by novocodev** [ChainSafe/mina-rs#204]
**Issue summary**
Q: I am building a rust library to be linked to a mobile app (iOS/android), I would like to interact with the mina blockchain from this library. Does/will mina-rs support this type of use case?

**Other information and links**

**Comment by willemolding** [comment]
That depends what kind of interaction you are looking for.

In the short term Mina-rs will allow for managing keys and signing transaction which can be forwarded to a public node. If you want to use chain state in your application you will be able to query this using the GraphQL API of a public node (no need for Mina-rs at all). This is a semi-trusted solution similar to MetaMask.

Further down the track it will support following the chain and managing state locally. This is a major milestone we are working toward but it is still some way off. This will significantly reduce the trust requirements on public nodes but will not add extra capabilities.

**Comment by novocodev** [comment]
Naively I want to generate zkSnark proofs locally and publish the proof to the chain (via a transaction?), I may also want to query the chain state.

From your response it sounds like I can achieve this now, but the implementation will improve over time?

Are there any docs/examples about how to bootstrap mina-rs with public node or discover at runtime?
