### ISSUE TITLE
Create Merkle Mask traits

### ISSUE THREAD

**Issue by mmacedoeu** [ChainSafe/mina-rs#41]
**Task summary**

Create traits:
- [ ] Maskable Merkle tree trait
- [ ] Masking Merkle tree trait

**Specification reference**

- 

**Other information and links**

https://github.com/MinaProtocol/mina/blob/develop/src/lib/merkle_mask/maskable_merkle_tree_intf.ml
https://github.com/MinaProtocol/mina/blob/develop/src/lib/merkle_mask/masking_merkle_tree_intf.ml

**Comment by noot** [comment]
what is the difference between these two traits? is there any more description of what they are?

**Comment by mmacedoeu** [comment]
> what is the difference between these two traits? is there any more description of what they are?

Updated with links for more information
