### ISSUE TITLE
Moving bin prot wire-protocol related crates under /protocol

### ISSUE THREAD

**Issue by creativcoder** [ChainSafe/mina-rs#77]
**Issue summary**

Proposing a crate re-org effort before closing M1. Current the bin-prot test related code are spread at the root directory. Thinking of having a protocol/ directory at root which would contain everything that has to do with wire protocol and bin prot related.

So here's what the updated workspace Cargo.toml would look like after this refactor:

```
[workspace]
members = [
	"base",
	"consensus",
	"crypto",
    # All crates related to bin prot wire protocol
	"protocol/bin-prot",
	"protcol/wire-type",
	"protocol/bin_prot_checker",
	"protocol/wire-type-derive",
	"protocol/test-fixtures",
	"protocol/test-serialization",
]
```

Accordingly the dependent crates would update their `Cargo.toml` for crates in protocol/

Open to re-org for other crates as well.

Thoughts?

**Other information and links**

**Comment by polarbeargo** [comment]
cargo build & cargo test successful
![Screenshot (234)](https://user-images.githubusercontent.com/8589224/140701922-0fcf0891-bb53-4553-9d8a-e6d1101cc216.png)
![Screenshot (235)](https://user-images.githubusercontent.com/8589224/140701946-8a6cf781-7bc4-4fc8-9515-d970d54039ac.png)
.
